### ISSUE TITLE
nativescript with angular

### ISSUE THREAD

**Issue by alihbuzaid** [KallynGowdy/nativescript-plugin-firebase#6]
what is the appropriate method to use the plugin with the angular implantation

I headed into multiple issues ...

thanks

**Comment by KallynGowdy** [comment]
@Sndan There's no specific method that I am aware of to get this library to work with Angular in NativeScript. So, I can't really help you out with that question.

If there's a specific problem that you want addressed, then bring it forward and I can try to help from there.

Otherwise, you can [check out the project](https://github.com/EddyVerbruggen/nativescript-plugin-firebase) that this library is derived from, which currently has much better support for the latest and greatest versions of NativeScript and Angular.

I'm going to close this issue. If you have a specific problem that you would like help with, please make another issue and we can go from there :)
